export const data = [
    {name: "Joseph", reviewImg:"./Cheapestessay.webp", text: "This is an excellent product. Thanks a lot.", date: "December 4,2021", id: "Customer #364978" },
    {img: "./writer-2.webp", name: "Jems Kennon"},
    {name: "Jamiu kazeem", reviewImg:"./Cheapestessay.webp", text: "Cooperative writer wh developed great work", date: "December 4,2021", id: "Customer #364978" },
    {name: "Abram Cordova", reviewImg:"./sitejabber.webp", text: "I have nothing much to say but, you did an amazing job!", date: "December 4,2021", id: "Customer #364978" },
    {name: "Maegan", reviewImg:"./trustpilot.webp", text: "The writer did a great job by following all the instructions and gave me a perfect work.", date: "December 4,2021", id: "Customer #364978" },
    {name: "Juan García", reviewImg:"./trustpilot.webp", text: "Some instructions were missed so I got less marks there was no plagiarism. Overall ok.", date: "December 4,2021", id: "Customer #364978" },
    {name: "Gavin Duran", reviewImg:"./sitejabber.webp", text: "Perfect", date: "December 4,2021", id: "Customer #364978" },
    {name: "Rahman Nugar", reviewImg:"./trustpilot.webp", text: "Well written and well done , have no doubt recommending you as a writer . I m very much satisfied with your work , keep up the good work.    I going to put another order today , you surely be my writer again.    If I have changes I will let you know.    Thank you again", date: "December 4,2021", id: "Customer #364978" },   
    {img: "./writer-5.webp", name: "Jems Kennon"},
    {name: "Charlene Angeles", reviewImg:"./sitejabber.webp", text: "I have nothing much to say but, you did an amazing job!", date: "December 4,2021", id: "Customer #364978" },
    {name: "Nanol Katil", reviewImg:"./sitejabber.webp", text: "Followed directions well and wrote a very solid Paper, Can't wait to see my grade!", date: "December 4,2021", id: "Customer #364978" },
    {name: "James Piatt", reviewImg:"./Cheapestessay.webp", text: "Amazing work!!", date: "December 4,2021", id: "Customer #364978" },
    {img: "./writer-4.webp", name: "Jems Kennon"},
    {name: "Ethan Paul", reviewImg:"./trustpilot.webp", text: "Thank You for your hard work.", date: "December 4,2021", id: "Customer #364978" },
    {name: "Ellen Read", reviewImg:"./Cheapestessay.webp", text: "The best and I mean the best paper I received since a long long time. I really appreciate all the work this writer did in such a short time. Followed all the instructions and for once I don’t have to ask for revision.", date: "December 4,2021", id: "Customer #364978" },
]